### ISSUE TITLE
scorecam of batch size more than 1

### ISSUE THREAD

**Issue by umairjavaid** [haofanwang/Score-CAM#1]
How are you generating cams when batch_size is more than one? In your implementation there is only one loop which iterates over number of activations but no loop for when batch_size is more than one. Your implementation only returns one activation, I am assuming it does not return multiple cams, when multiple images are given as input

**Comment by haofanwang** [comment]
Yes, @umairjavaid  batch generation is not supported now. I will add it later. If you are interested in, it would be appreciated to PR.

**Comment by umairjavaid** [comment]
Actually, yes, I have implemented scorecam with batch generation. I am new to github, can u guide me how to contribute. Thank you

**Comment by haofanwang** [comment]
That's great @umairjavaid. If your implementation is based on mine, then you can directly click "New pull request" and I can see it.
