### ISSUE TITLE
I have some questions about paper and your implementation. 

### ISSUE THREAD

**Issue by jeongHwarr** [haofanwang/Score-CAM#13]
Hello. I'm impressed with the idea of ​​this paper and want to apply it to my project. 
But there was an incomprehensible part between your thesis and code implementation.

In my understanding, CIC means difference between target score of original input image and target score multiplied by Mask and input image. Did I get it wrong?

In CIC, doesn't  $X_b$ mean the input image? In your implementation, you used the target score for the mask multiplied by the input image to get the CIC. The target score for the original image is not subtracted. I can't understand this part very well. I want to know what I misunderstood. 

Thank you!

**Comment by haofanwang** [comment]
Hi, @jeongHwarr. Thanks for your interest!

`X_b` is not the input image, it is a baseline. In my implementation, I just use a black image (all zeros) as a baseline, so you can ignore `X_b` here. Then the CIC is just the [classification score](https://github.com/haofanwang/Score-CAM/blob/b42878256400965c2cedd7c5c335a416cacd7cc3/cam/scorecam.py#L64) of the masked input. If you are interested, you can try to use the input image as a baseline, it should also be fine.

Please let me know if you have further questions to apply this method to your project, I'm willing to help.

**Comment by jeongHwarr** [comment]
@haofanwang Okay I got it! Thank you for your reply
