### ISSUE TITLE
Implementation for Energy-based Point Game

### ISSUE THREAD

**Issue by haofanwang** [haofanwang/Score-CAM#16]
I have received many emails about releasing the code for Energy-based Point Game (a modified evaluation metric proposed in our paper), to promote the reproducibility of the research, I will release the code recently (I'm working on NeurIPS reviewing process now, I will clean up the code later). Thanks for your patience!

**Comment by haofanwang** [comment]
[https://github.com/haofanwang/Score-CAM/blob/master/utils/energyPointGame.py](https://github.com/haofanwang/Score-CAM/blob/master/utils/energyPointGame.py)

**Comment by noobgrow** [comment]
Sir, can you provide the other evaluation code like Average Drop/Incr. in Confidence/Insertion /Deletion ?Thanks a lot!
