### ISSUE TITLE
Visualization Issue

### ISSUE THREAD

**Issue by Halilibrahimaysel** [haofanwang/Score-CAM#19]
Hello Haofan, 
I have simply attached a code example to show what I need on the example for GradCAM given by Keras and added comments on crucial points.

Thanks in advance,

Halil
[GradCAM1.zip](https://github.com/haofanwang/Score-CAM/files/7189961/GradCAM1.zip)

**Comment by haofanwang** [comment]
@Halilibrahimaysel 

I don't think it is a problem actually, the reason why the background is totally black is that the tiny values are set to zero (np.unit8 matters here, and also different visualization tools may have some variances). Just follow the code below should be fine.

```
heatmap = cam(original_img)
upsampled_heatmap = upsample_func(heatmap, target_size)
result = upsampled_heatmap * original_img
```

**Comment by Halilibrahimaysel** [comment]
Thank you so much for the answer. I think as you mentioned it is not a
problem as keeping the background black or gray does not make a substantial
difference anyway.


Haofan Wang ***@***.***>, 20 Eyl 2021 Pzt, 04:23 tarihinde
şunu yazdı:
