### ISSUE TITLE
How to visualize my own model?

### ISSUE THREAD

**Issue by alwayslj** [haofanwang/Score-CAM#2]

**Comment by haofanwang** [comment]
Hi @alwayslj,  you can refer to [basecam.py](https://github.com/haofanwang/Score-CAM/blob/master/cam/basecam.py). If your model is not in torchvision.models, you may need to modify the [find_layer](https://github.com/haofanwang/Score-CAM/blob/a5ad60dca576d99b1552ec2ad8c9ef4539077608/cam/basecam.py#L60) function to suit your own model. Please let me know if you have any trouble.

I will add an example to support self-defined model soon.

**Comment by abhigoku10** [comment]
@haofanwang for a models like Faster RCNN and MaskRCNN which layer_name should be passed ??

**Comment by haofanwang** [comment]
Hi, @abhigoku10, you are free to select a feature layer, for example, the last conv layer. You can directly print the model and get the name of a specific layer.

**Comment by abhigoku10** [comment]
@haofanwang does this principle work even for object detection architectures ?? there should be some modifications for this right

**Comment by haofanwang** [comment]
@abhigoku10 As far as I know, detection model usually has a classification branch. So you can use the middle feature as the activation map, and the classification score as weight. You can treat it as a self-defined model, the only thing you need to modify is to hook the activation output [(this file).](https://github.com/haofanwang/Score-CAM/blob/a5ad60dca576d99b1552ec2ad8c9ef4539077608/utils/__init__.py#L585)

**Comment by abhigoku10** [comment]
@haofanwang thanks for the response I was able to hardcode the layer which i required and was able to get the activation map from it but to pass the classification score as weight how to do it since mine is detection/segmentation model I directly get the probability scores should I pass these values as weight

**Comment by haofanwang** [comment]
@abhigoku10  Yes, you can try to use the probability score as weight, but I'm not sure whether it works well.
