### ISSUE TITLE
does it work for RNN model

### ISSUE THREAD

**Issue by ran337287** [haofanwang/Score-CAM#21]
does it work for RNN+CNN model whose task is text classification

**Comment by haofanwang** [comment]
Is it CNN+RNN model? @ran337287 

I found some resources that may be helpful for your reference. Once Grad-CAM applies, so does Score-CAM.

https://discuss.pytorch.org/t/cam-grad-cnn-lstm/88679

https://github.com/OverLordGoldDragon/see-rnn/issues/4

**Comment by haofanwang** [comment]
Not active. Closed.
