### ISSUE TITLE
Grid Effects

### ISSUE THREAD

**Issue by WesRobbins** [haofanwang/Score-CAM#22]
I am only getting strong activations along a grid pattern. Attached image shows 1,000 averaged activation maps which highlights grid. Is there a known reason for this effect?

I am using a standard resnet implementation with dilation set to 1 on all conv layers
![grid-activations](https://user-images.githubusercontent.com/51028165/157570514-225d9bb4-6359-4c5f-98d6-9549c6966c28.png)

**Comment by haofanwang** [comment]
What is the original input? Is it a checkerboard？

**Comment by WesRobbins** [comment]
face images (e.g LFW, MS Celeb)

**Comment by haofanwang** [comment]
It looks weird. What is the classifier?
