### ISSUE TITLE
Point Game Function

### ISSUE THREAD

**Issue by RuoyuChen10** [haofanwang/Score-CAM#23]
Would you please offer your `Point Game` code for an evaluation? Thanks.

**Comment by haofanwang** [comment]
@RuoyuChen10 

The implementation of Point Game should be easy. It works by checking whether the maximum point of map falls into the bounding box. I have provided Energy-based Point Game for your reference, slight modification should be fine.

**Comment by RuoyuChen10** [comment]
> @RuoyuChen10
> 
> The implementation of Point Game should be easy. It works by checking whether the maximum point of map falls into the bounding box. I have provided Energy-based Point Game for your reference, slight modification should be fine.

Thanks for your reply, and I also have a question, if there are multi objects in the model, how can I quantity the PG metric? For example, in the classification task, there are two cats in the image and two bounding boxes, if the maximum point of the map falls into one of the boxes it's ok? Thanks.

**Comment by haofanwang** [comment]
For multi-objects localization, I would suggest you adopt our Energy-based Point Game instead of Point Game. Otherwise, the score of Point Game will be inflated as the maximum has higher possibility falling into bbox.
