### ISSUE TITLE
Which layer's feature should be used?

### ISSUE THREAD

**Issue by kai-wen-yang** [haofanwang/Score-CAM#24]
Hi, I want to visualize my datasets on ResNet50. I wonder which layers' feature map should be used. My data's resolution is 28x28.

**Comment by haofanwang** [comment]
You can refer [this](https://github.com/haofanwang/Score-CAM/blob/45045ed2782459725f78884adb3eec4e0e069c9e/utils/__init__.py#L322). In most cases, you can use the last layer before pooling.

**Comment by kai-wen-yang** [comment]
Thanks, the last layer is good.
