### ISSUE TITLE
Could you please provide the feature importance included dataset that has been generated?

### ISSUE THREAD

**Issue by bosaiiasliu** [haofanwang/Score-CAM#25]
I found that using ScoreCAM to generate feature importance interpretations is slow, taking about 2 seconds for one image. If I want to generate all the image explanations in the Imagenet dataset, the time it takes seems very long. Or, is there a suitable acceleration method?

**Comment by haofanwang** [comment]
Hi, @bosaiiasliu 

I found a [speed-up version](https://github.com/tabayashi0117/Score-CAM) of Score-CAM, which only selected channels with large variances as mask images. By the way, why you want to generate features over the whole ImageNet? In most of case, we just randomly sample a small portion from it.

**Comment by bosaiiasliu** [comment]
Because I found through experiments on CIFAR10 that pictures with feature importance are likely to be a useful data augmentation method. I want to try it on ImageNet. Unfortunately, I found that someone has already done something similar. [https://arxiv.org/abs/2006.01791](url)
